version: '3.4'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=SqlViews
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
